<?php

declare(strict_types=1);

/**
 * Locale data for 'ne'.
 * Created: Tue, 01 Nov 2022 12:00:29 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_ne_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '¤ #,%f';
        $this->currencyNegativeFormat = '¤ #,%f';
        $this->language = 'ne';
        $this->locale = 'ne';
        $this->firstDayWeek = 1;
        $this->longDate = 'Y F j';
        $this->shortDate = 'Y M j';
        $this->longTime = 'H:i:s';
        $this->shortTime = 'H:i';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'पूर्वाह्न';
        $this->pmString = 'अपराह्न';
        $this->nameEnglish = 'Nepali';
        $this->nameNative = 'नेपाली';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'जनवरी',
                    2  => 'फेब्रुअरी',
                    3  => 'मार्च',
                    4  => 'अप्रिल',
                    5  => 'मे',
                    6  => 'जुन',
                    7  => 'जुलाई',
                    8  => 'अगस्ट',
                    9  => 'सेप्टेम्बर',
                    10 => 'अक्टोबर',
                    11 => 'नोभेम्बर',
                    12 => 'डिसेम्बर',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'जन',
                    2  => 'फेब',
                    3  => 'मार्च',
                    4  => 'अप्र',
                    5  => 'मे',
                    6  => 'जुन',
                    7  => 'जुल',
                    8  => 'अग',
                    9  => 'सेप',
                    10 => 'अक्टो',
                    11 => 'नोभे',
                    12 => 'डिसे',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'जनवरी',
                    2  => 'फेब्रुअरी',
                    3  => 'मार्च',
                    4  => 'अप्रिल',
                    5  => 'मे',
                    6  => 'जुन',
                    7  => 'जुलाई',
                    8  => 'अगस्ट',
                    9  => 'सेप्टेम्बर',
                    10 => 'अक्टोबर',
                    11 => 'नोभेम्बर',
                    12 => 'डिसेम्बर',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'आइत',
                    1 => 'सोम',
                    2 => 'मङ्गल',
                    3 => 'बुध',
                    4 => 'बिहि',
                    5 => 'शुक्र',
                    6 => 'शनि',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'आ',
                    1 => 'सो',
                    2 => 'म',
                    3 => 'बु',
                    4 => 'बि',
                    5 => 'शु',
                    6 => 'श',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'आइतबार',
                    1 => 'सोमबार',
                    2 => 'मङ्गलबार',
                    3 => 'बुधबार',
                    4 => 'बिहिबार',
                    5 => 'शुक्रबार',
                    6 => 'शनिबार',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, one {# वर्ष} other {# वर्ष}}',
            'month'       => '{n, plural, one {# महिना} other {# महिना}}',
            'week'        => '{n, plural, one {# हप्ता} other {# हप्ता}}',
            'day'         => '{n, plural, one {# दिन} other {# दिन}}',
            'hour'        => '{n, plural, one {# घण्टा} other {# घण्टा}}',
            'minute'      => '{n, plural, one {# मिनेट} other {# मिनेट}}',
            'second'      => '{n, plural, one {# सेकेन्ड} other {# सेकेन्ड}}',
            'millisecond' => '{n, plural, one {# मि.से.} other {# मि.से.}}',
            'microsecond' => '{n, plural, one {# मा.से.} other {# मा.से.}}',
            'nanosecond'  => '{n, plural, one {# न.से.} other {# न.से.}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
