<?php
declare(strict_types=1);

/**
 * Locale data for 'pl-PL'.
 * Created: Sun, 22 Nov 2020 20:21:41 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_pl_PL_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = ' ';
        $this->currencyFormat = '%f ¤';
        $this->currencyNegativeFormat = '(%f ¤)';
        $this->language = 'pl';
        $this->locale = 'pl-PL';
        $this->firstDayWeek = 1;
        $this->longDate = 'j F Y';
        $this->shortDate = 'j M Y';
        $this->longTime = 'H:i:s';
        $this->shortTime = 'H:i';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'AM';
        $this->pmString = 'PM';
        $this->nameEnglish = 'Polish (Poland)';
        $this->nameNative = 'Polski (Polska)';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'Sty',
                      2 => 'Lut',
                      3 => 'Mar',
                      4 => 'Kwi',
                      5 => 'Maj',
                      6 => 'Cze',
                      7 => 'Lip',
                      8 => 'Sie',
                      9 => 'Wrz',
                      10 => 'Paź',
                      11 => 'Lis',
                      12 => 'Gru',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => 'S',
                      2 => 'L',
                      3 => 'M',
                      4 => 'K',
                      5 => 'M',
                      6 => 'C',
                      7 => 'L',
                      8 => 'S',
                      9 => 'W',
                      10 => 'P',
                      11 => 'L',
                      12 => 'G',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'Stycznia',
                      2 => 'Lutego',
                      3 => 'Marca',
                      4 => 'Kwietnia',
                      5 => 'Maja',
                      6 => 'Czerwca',
                      7 => 'Lipca',
                      8 => 'Sierpnia',
                      9 => 'Września',
                      10 => 'Października',
                      11 => 'Listopada',
                      12 => 'Grudnia',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'Niedz.',
                      1 => 'Pon.',
                      2 => 'Wt.',
                      3 => 'śr.',
                      4 => 'Czw.',
                      5 => 'Pt.',
                      6 => 'Sob.',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'N',
                      1 => 'P',
                      2 => 'W',
                      3 => 'ś',
                      4 => 'C',
                      5 => 'P',
                      6 => 'S',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'Niedziela',
                      1 => 'Poniedziałek',
                      2 => 'Wtorek',
                      3 => 'środa',
                      4 => 'Czwartek',
                      5 => 'Piątek',
                      6 => 'Sobota',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, one {# rok} one {# rok} one {# rokowi} one {# roku} one {# rokiem} one {# roku} one {# roku} few {# lata} few {# lata} few {# latom} few {# lat} few {# latami} few {# latach} few {# lata} many {# lat} many {# lat} many {# latom} many {# lat} many {# latami} many {# latach} many {# lat} other {# roku} other {# roku} other {# roku} other {# roku} other {# roku} other {# roku} other {# roku}}',
              'month' => '{n, plural, one {# miesiąc} one {# miesiąc} one {# miesiącowi} one {# miesiąca} one {# miesiącem} one {# miesiącu} one {# miesiącu} few {# miesiące} few {# miesiące} few {# miesiącom} few {# miesięcy} few {# miesiącami} few {# miesiącach} few {# miesiące} many {# miesięcy} many {# miesięcy} many {# miesiącom} many {# miesięcy} many {# miesiącami} many {# miesiącach} many {# miesięcy} other {# miesiąca} other {# miesiąca} other {# miesiąca} other {# miesiąca} other {# miesiąca} other {# miesiąca} other {# miesiąca}}',
              'week' => '{n, plural, one {# tydzień} one {# tydzień} one {# tygodniowi} one {# tygodnia} one {# tygodniem} one {# tygodniu} one {# tygodniu} few {# tygodnie} few {# tygodnie} few {# tygodniom} few {# tygodni} few {# tygodniami} few {# tygodniach} few {# tygodnie} many {# tygodni} many {# tygodni} many {# tygodniom} many {# tygodni} many {# tygodniami} many {# tygodniach} many {# tygodni} other {# tygodnia} other {# tygodnia} other {# tygodnia} other {# tygodnia} other {# tygodnia} other {# tygodnia} other {# tygodnia}}',
              'day' => '{n, plural, one {# doba} one {# dobę} one {# dobie} one {# doby} one {# dobą} one {# dobie} one {# dobo} few {# doby} few {# doby} few {# dobom} few {# dób} few {# dobami} few {# dobach} few {# doby} many {# dób} many {# dób} many {# dobom} many {# dób} many {# dobami} many {# dobach} many {# dób} other {# doby} other {# doby} other {# doby} other {# doby} other {# doby} other {# doby} other {# doby}}',
              'hour' => '{n, plural, one {# godz.} few {# godz.} many {# godz.} other {# godz.}}',
              'second' => '{n, plural, one {# sek.} few {# sek.} many {# sek.} other {# sek.}}',
              'minute' => '{n, plural, one {# min} other {# min}}',
              'millisecond' => '{n, plural, one {# ms} other {# ms}}',
              'microsecond' => '{n, plural, one {# µs} other {# µs}}',
              'nanosecond' => '{n, plural, one {# ns} other {# ns}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
