<?php

declare(strict_types=1);

/**
 * Locale data for 'mni-Beng'.
 * Created: Tue, 01 Nov 2022 12:00:28 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_mni_Beng_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'mni';
        $this->locale = 'mni-Beng';
        $this->firstDayWeek = 1;
        $this->longDate = 'F j, Y';
        $this->shortDate = 'M j, Y';
        $this->longTime = 'g:i:s A';
        $this->shortTime = 'g:i A';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'এ এম';
        $this->pmString = 'পি এম';
        $this->nameEnglish = 'English';
        $this->nameNative = 'English';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'জানুৱারি',
                    2  => 'ফেব্রুৱারি',
                    3  => 'মার্চ',
                    4  => 'এপ্রিল',
                    5  => 'মে',
                    6  => 'জুন',
                    7  => 'জুলাই',
                    8  => 'আগস্ট',
                    9  => 'সেপ্টেম্বর',
                    10 => 'ওক্টোবর',
                    11 => 'নভেম্বর',
                    12 => 'ডিসেম্বর',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'জা',
                    2  => 'ফে',
                    3  => 'মার',
                    4  => 'এপ',
                    5  => 'মে',
                    6  => 'জুন',
                    7  => 'জুল',
                    8  => 'আ',
                    9  => 'সে',
                    10 => 'ওক',
                    11 => 'নব',
                    12 => 'ডি',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'জানুৱারি',
                    2  => 'ফেব্রুৱারি',
                    3  => 'মার্চ',
                    4  => 'এপ্রিল',
                    5  => 'মে',
                    6  => 'জুন',
                    7  => 'জুলাই',
                    8  => 'আগস্ট',
                    9  => 'সেপ্টেম্বর',
                    10 => 'ওক্টোবর',
                    11 => 'নভেম্বর',
                    12 => 'ডিসেম্বর',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'নোংমাইজিং',
                    1 => 'নিংথৌকাবা',
                    2 => 'লৈবাকপোকপা',
                    3 => 'য়ুমশকৈশা',
                    4 => 'শগোলশেন',
                    5 => 'ইরাই',
                    6 => 'থাংজ',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'নোং',
                    1 => 'নিং',
                    2 => 'লৈবা',
                    3 => 'য়ুম',
                    4 => 'শগো',
                    5 => 'ইরা',
                    6 => 'থাং',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'নোংমাইজিং',
                    1 => 'নিংথৌকাবা',
                    2 => 'লৈবাকপোকপা',
                    3 => 'য়ুমশকৈশা',
                    4 => 'শগোলশেন',
                    5 => 'ইরাই',
                    6 => 'থাংজ',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, one {# year} other {# years}}',
            'month'       => '{n, plural, one {# month} other {# months}}',
            'week'        => '{n, plural, one {# week} other {# weeks}}',
            'day'         => '{n, plural, one {# day} other {# days}}',
            'hour'        => '{n, plural, one {# hr} other {# hr}}',
            'minute'      => '{n, plural, one {# min} other {# min}}',
            'second'      => '{n, plural, one {# sec} other {# sec}}',
            'millisecond' => '{n, plural, one {# ms} other {# ms}}',
            'microsecond' => '{n, plural, one {# μs} other {# μs}}',
            'nanosecond'  => '{n, plural, one {# ns} other {# ns}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
