<?php
declare(strict_types=1);

/**
 * Locale data for 'uz-Cyrl'.
 * Created: Sun, 22 Nov 2020 20:21:59 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_uz_Cyrl_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = ' ';
        $this->currencyFormat = '%f ¤';
        $this->currencyNegativeFormat = '%f ¤';
        $this->language = 'uz';
        $this->locale = 'uz-Cyrl';
        $this->firstDayWeek = 1;
        $this->longDate = 'j F, Y';
        $this->shortDate = 'j M, Y';
        $this->longTime = 'H:i:s';
        $this->shortTime = 'H:i';
        $this->dateTime = '%date% %time%';
        $this->amString = 'ТО';
        $this->pmString = 'ТК';
        $this->nameEnglish = 'Uzbek';
        $this->nameNative = 'O‘zbek';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'янв',
                      2 => 'фев',
                      3 => 'мар',
                      4 => 'апр',
                      5 => 'май',
                      6 => 'июн',
                      7 => 'июл',
                      8 => 'авг',
                      9 => 'сен',
                      10 => 'окт',
                      11 => 'ноя',
                      12 => 'дек',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => 'Я',
                      2 => 'Ф',
                      3 => 'М',
                      4 => 'А',
                      5 => 'М',
                      6 => 'И',
                      7 => 'И',
                      8 => 'А',
                      9 => 'С',
                      10 => 'О',
                      11 => 'Н',
                      12 => 'Д',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'январ',
                      2 => 'феврал',
                      3 => 'март',
                      4 => 'апрел',
                      5 => 'май',
                      6 => 'июн',
                      7 => 'июл',
                      8 => 'август',
                      9 => 'сентябр',
                      10 => 'октябр',
                      11 => 'ноябр',
                      12 => 'декабр',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'якш',
                      1 => 'душ',
                      2 => 'сеш',
                      3 => 'чор',
                      4 => 'пай',
                      5 => 'жум',
                      6 => 'шан',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'Я',
                      1 => 'Д',
                      2 => 'С',
                      3 => 'Ч',
                      4 => 'П',
                      5 => 'Ж',
                      6 => 'Ш',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'якшанба',
                      1 => 'душанба',
                      2 => 'сешанба',
                      3 => 'чоршанба',
                      4 => 'пайшанба',
                      5 => 'жума',
                      6 => 'шанба',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, one {# йил} other {# йил}}',
              'month' => '{n, plural, one {# ой} other {# ой}}',
              'week' => '{n, plural, one {# ҳафта} other {# ҳафта}}',
              'day' => '{n, plural, one {# кун} other {# кун}}',
              'hour' => '{n, plural, one {# соат} other {# соат}}',
              'minute' => '{n, plural, one {# дақ} other {# дақ}}',
              'second' => '{n, plural, one {# сония} other {# сония}}',
              'millisecond' => '{n, plural, one {# мс} other {# мс}}',
              'microsecond' => '{n, plural, one {# mks} other {# mks}}',
              'nanosecond' => '{n, plural, one {# ns} other {# ns}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
