<?php

declare(strict_types=1);

/**
 * Locale data for 'yo-BJ'.
 * Created: Tue, 01 Nov 2022 12:00:36 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_yo_BJ_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'yo';
        $this->locale = 'yo-BJ';
        $this->firstDayWeek = 1;
        $this->longDate = 'j M Y';
        $this->shortDate = 'j m Y';
        $this->longTime = 'G:i:s';
        $this->shortTime = 'G:i';
        $this->dateTime = '%date% %time%';
        $this->amString = 'Àárɔ̀';
        $this->pmString = 'Ɔ̀sán';
        $this->nameEnglish = 'Yoruba (Benin)';
        $this->nameNative = 'Èdè Yorùbá (Bẹ̀nẹ̀)';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'Shɛ́r',
                    2  => 'Èrèl',
                    3  => 'Ɛrɛ̀n',
                    4  => 'Ìgb',
                    5  => 'Ɛ̀bi',
                    6  => 'Òkú',
                    7  => 'Agɛ',
                    8  => 'Ògú',
                    9  => 'Owe',
                    10 => 'Ɔ̀wà',
                    11 => 'Bél',
                    12 => 'Ɔ̀pɛ',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'S',
                    2  => 'È',
                    3  => 'Ɛ',
                    4  => 'Ì',
                    5  => 'Ɛ̀',
                    6  => 'Ò',
                    7  => 'A',
                    8  => 'Ò',
                    9  => 'O',
                    10 => 'Ɔ̀',
                    11 => 'B',
                    12 => 'Ɔ̀',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'Oshù Shɛ́rɛ́',
                    2  => 'Oshù Èrèlè',
                    3  => 'Oshù Ɛrɛ̀nà',
                    4  => 'Oshù Ìgbé',
                    5  => 'Oshù Ɛ̀bibi',
                    6  => 'Oshù Òkúdu',
                    7  => 'Oshù Agɛmɔ',
                    8  => 'Oshù Ògún',
                    9  => 'Oshù Owewe',
                    10 => 'Oshù Ɔ̀wàrà',
                    11 => 'Oshù Bélú',
                    12 => 'Oshù Ɔ̀pɛ̀',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'À',
                    1 => 'A',
                    2 => 'Ì',
                    3 => 'Ɔ',
                    4 => 'Ɔ',
                    5 => 'Ɛ',
                    6 => 'À',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'Ɔjɔ́ Àìkú',
                    1 => 'Ɔjɔ́ Ajé',
                    2 => 'Ɔjɔ́ Ìsɛ́gun',
                    3 => 'Ɔjɔ́rú',
                    4 => 'Ɔjɔ́bɔ',
                    5 => 'Ɔjɔ́ Ɛtì',
                    6 => 'Ɔjɔ́ Àbámɛ́ta',
                ];
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'Àìk',
                    1 => 'Aj',
                    2 => 'Ìsɛ́g',
                    3 => 'Ɔjɔ́r',
                    4 => 'Ɔjɔ́b',
                    5 => 'Ɛt',
                    6 => 'Àbám',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, other {# ɔd}}',
            'month'       => '{n, plural, other {# oshù}}',
            'week'        => '{n, plural, other {# ɔsh}}',
            'day'         => '{n, plural, other {ɔj #}}',
            'minute'      => '{n, plural, other {# ìsh}}',
            'second'      => '{n, plural, other {# ìsh àáy}}',
            'hour'        => '{n, plural, other {# wkt}}',
            'millisecond' => '{n, plural, one {# ms} other {# ms}}',
            'microsecond' => '{n, plural, one {# μs} other {# μs}}',
            'nanosecond'  => '{n, plural, one {# ns} other {# ns}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
