<?php

declare(strict_types=1);

/**
 * Locale data for 'ki'.
 * Created: Tue, 01 Nov 2022 12:00:26 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_ki_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'ki';
        $this->locale = 'ki';
        $this->firstDayWeek = 1;
        $this->longDate = 'j F Y';
        $this->shortDate = 'j M Y';
        $this->longTime = 'H:i:s';
        $this->shortTime = 'H:i';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'Kiroko';
        $this->pmString = 'Hwaĩ-inĩ';
        $this->nameEnglish = 'Kikuyu';
        $this->nameNative = 'Gikuyu';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'J',
                    2  => 'K',
                    3  => 'G',
                    4  => 'K',
                    5  => 'G',
                    6  => 'G',
                    7  => 'M',
                    8  => 'K',
                    9  => 'K',
                    10 => 'I',
                    11 => 'I',
                    12 => 'D',
                ];
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'JEN',
                    2  => 'WKR',
                    3  => 'WGT',
                    4  => 'WKN',
                    5  => 'WTN',
                    6  => 'WTD',
                    7  => 'WMJ',
                    8  => 'WNN',
                    9  => 'WKD',
                    10 => 'WIK',
                    11 => 'WMW',
                    12 => 'DIT',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'Njenuarĩ',
                    2  => 'Mwere wa kerĩ',
                    3  => 'Mwere wa gatatũ',
                    4  => 'Mwere wa kana',
                    5  => 'Mwere wa gatano',
                    6  => 'Mwere wa gatandatũ',
                    7  => 'Mwere wa mũgwanja',
                    8  => 'Mwere wa kanana',
                    9  => 'Mwere wa kenda',
                    10 => 'Mwere wa ikũmi',
                    11 => 'Mwere wa ikũmi na ũmwe',
                    12 => 'Ndithemba',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'K',
                    1 => 'N',
                    2 => 'N',
                    3 => 'N',
                    4 => 'A',
                    5 => 'N',
                    6 => 'N',
                ];
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'KMA',
                    1 => 'NTT',
                    2 => 'NMN',
                    3 => 'NMT',
                    4 => 'ART',
                    5 => 'NMA',
                    6 => 'NMM',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'Kiumia',
                    1 => 'Njumatatũ',
                    2 => 'Njumaine',
                    3 => 'Njumatana',
                    4 => 'Aramithi',
                    5 => 'Njumaa',
                    6 => 'Njumamothi',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, one {# year} other {# years}}',
            'month'       => '{n, plural, one {# month} other {# months}}',
            'week'        => '{n, plural, one {# week} other {# weeks}}',
            'day'         => '{n, plural, one {# day} other {# days}}',
            'hour'        => '{n, plural, one {# hr} other {# hr}}',
            'minute'      => '{n, plural, one {# min} other {# min}}',
            'second'      => '{n, plural, one {# sec} other {# sec}}',
            'millisecond' => '{n, plural, one {# ms} other {# ms}}',
            'microsecond' => '{n, plural, one {# μs} other {# μs}}',
            'nanosecond'  => '{n, plural, one {# ns} other {# ns}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
