<?php

declare(strict_types=1);

/**
 * Locale data for 'et-EE'.
 * Created: Tue, 01 Nov 2022 12:00:22 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_et_EE_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = ' ';
        $this->currencyFormat = '%f ¤';
        $this->currencyNegativeFormat = '(%f ¤)';
        $this->language = 'et';
        $this->locale = 'et-EE';
        $this->firstDayWeek = 1;
        $this->longDate = 'j. F Y';
        $this->shortDate = 'j. M Y';
        $this->longTime = 'H:i:s';
        $this->shortTime = 'H:i';
        $this->dateTime = '%date% %time%';
        $this->amString = 'AM';
        $this->pmString = 'PM';
        $this->nameEnglish = 'Estonian (Estonia)';
        $this->nameNative = 'Eesti (Eesti)';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'Jaan',
                    2  => 'Veebr',
                    3  => 'Märts',
                    4  => 'Apr',
                    5  => 'Mai',
                    6  => 'Juuni',
                    7  => 'Juuli',
                    8  => 'Aug',
                    9  => 'Sept',
                    10 => 'Okt',
                    11 => 'Nov',
                    12 => 'Dets',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'J',
                    2  => 'V',
                    3  => 'M',
                    4  => 'A',
                    5  => 'M',
                    6  => 'J',
                    7  => 'J',
                    8  => 'A',
                    9  => 'S',
                    10 => 'O',
                    11 => 'N',
                    12 => 'D',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'Jaanuar',
                    2  => 'Veebruar',
                    3  => 'Märts',
                    4  => 'Aprill',
                    5  => 'Mai',
                    6  => 'Juuni',
                    7  => 'Juuli',
                    8  => 'August',
                    9  => 'September',
                    10 => 'Oktoober',
                    11 => 'November',
                    12 => 'Detsember',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'P',
                    1 => 'E',
                    2 => 'T',
                    3 => 'K',
                    4 => 'N',
                    5 => 'R',
                    6 => 'L',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'P',
                    1 => 'E',
                    2 => 'T',
                    3 => 'K',
                    4 => 'N',
                    5 => 'R',
                    6 => 'L',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'Pühapäev',
                    1 => 'Esmaspäev',
                    2 => 'Teisipäev',
                    3 => 'Kolmapäev',
                    4 => 'Neljapäev',
                    5 => 'Reede',
                    6 => 'Laupäev',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, one {# aasta} other {# aastat}}',
            'month'       => '{n, plural, one {# kuu} other {# kuud}}',
            'week'        => '{n, plural, one {# nädal} other {# nädalat}}',
            'day'         => '{n, plural, one {# ööpäev} other {# ööpäeva}}',
            'hour'        => '{n, plural, one {# t} other {# t}}',
            'minute'      => '{n, plural, one {# min} other {# min}}',
            'second'      => '{n, plural, one {# sek} other {# sek}}',
            'millisecond' => '{n, plural, one {# ms} other {# ms}}',
            'microsecond' => '{n, plural, one {# μs} other {# μs}}',
            'nanosecond'  => '{n, plural, one {# ns} other {# ns}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
