<?php
declare(strict_types=1);

/**
 * Locale data for 'lo-LA'.
 * Created: Sun, 22 Nov 2020 20:21:23 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_lo_LA_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = '.';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '¤-%f';
        $this->language = 'lo';
        $this->locale = 'lo-LA';
        $this->firstDayWeek = 0;
        $this->longDate = 'j F Y';
        $this->shortDate = 'j M Y';
        $this->longTime = 'G:i:s';
        $this->shortTime = 'G:i';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'ກ່ອນທ່ຽງ';
        $this->pmString = 'ຫຼັງທ່ຽງ';
        $this->nameEnglish = 'Lao (Laos)';
        $this->nameNative = 'ລາວ (ລາວ)';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'ມ.ກ.',
                      2 => 'ກ.ພ.',
                      3 => 'ມ.ນ.',
                      4 => 'ມ.ສ.',
                      5 => 'ພ.ພ.',
                      6 => 'ມິ.ຖ.',
                      7 => 'ກ.ລ.',
                      8 => 'ສ.ຫ.',
                      9 => 'ກ.ຍ.',
                      10 => 'ຕ.ລ.',
                      11 => 'ພ.ຈ.',
                      12 => 'ທ.ວ.',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => '1',
                      2 => '2',
                      3 => '3',
                      4 => '4',
                      5 => '5',
                      6 => '6',
                      7 => '7',
                      8 => '8',
                      9 => '9',
                      10 => '10',
                      11 => '11',
                      12 => '12',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'ມັງກອນ',
                      2 => 'ກຸມພາ',
                      3 => 'ມີນາ',
                      4 => 'ເມສາ',
                      5 => 'ພຶດສະພາ',
                      6 => 'ມິຖຸນາ',
                      7 => 'ກໍລະກົດ',
                      8 => 'ສິງຫາ',
                      9 => 'ກັນຍາ',
                      10 => 'ຕຸລາ',
                      11 => 'ພະຈິກ',
                      12 => 'ທັນວາ',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'ອາທິດ',
                      1 => 'ຈັນ',
                      2 => 'ອັງຄານ',
                      3 => 'ພຸດ',
                      4 => 'ພະຫັດ',
                      5 => 'ສຸກ',
                      6 => 'ເສົາ',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'ອາ',
                      1 => 'ຈ',
                      2 => 'ອ',
                      3 => 'ພ',
                      4 => 'ພຫ',
                      5 => 'ສຸ',
                      6 => 'ສ',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'ວັນອາທິດ',
                      1 => 'ວັນຈັນ',
                      2 => 'ວັນອັງຄານ',
                      3 => 'ວັນພຸດ',
                      4 => 'ວັນພະຫັດ',
                      5 => 'ວັນສຸກ',
                      6 => 'ວັນເສົາ',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, other {# ປີ}}',
              'month' => '{n, plural, other {# ເດືອນ}}',
              'week' => '{n, plural, other {# ອາທິດ}}',
              'day' => '{n, plural, other {# ມື້}}',
              'hour' => '{n, plural, other {# ຊມ}}',
              'minute' => '{n, plural, other {# ນທ}}',
              'second' => '{n, plural, other {# ວິ}}',
              'millisecond' => '{n, plural, other {# ມລວ}}',
              'microsecond' => '{n, plural, other {# μວິ}}',
              'nanosecond' => '{n, plural, other {# ນນ​ວິ}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
