<?php

declare(strict_types=1);

/**
 * Locale data for 'my'.
 * Created: Tue, 01 Nov 2022 12:00:29 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_my_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '¤ %f';
        $this->currencyNegativeFormat = '¤ %f';
        $this->language = 'my';
        $this->locale = 'my';
        $this->firstDayWeek = 1;
        $this->longDate = 'Y၊ F j';
        $this->shortDate = 'Y၊ M j';
        $this->longTime = 'G:i:s';
        $this->shortTime = 'G:i';
        $this->dateTime = '%date% %time%';
        $this->amString = 'နံနက်';
        $this->pmString = 'ညနေ';
        $this->nameEnglish = 'Myanmar Language';
        $this->nameNative = 'မြန်မာ';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'ဇန်',
                    2  => 'ဖေ',
                    3  => 'မတ်',
                    4  => 'ဧ',
                    5  => 'မေ',
                    6  => 'ဇွန်',
                    7  => 'ဇူ',
                    8  => 'ဩ',
                    9  => 'စက်',
                    10 => 'အောက်',
                    11 => 'နို',
                    12 => 'ဒီ',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'ဇ',
                    2  => 'ဖ',
                    3  => 'မ',
                    4  => 'ဧ',
                    5  => 'မ',
                    6  => 'ဇ',
                    7  => 'ဇ',
                    8  => 'ဩ',
                    9  => 'စ',
                    10 => 'အ',
                    11 => 'န',
                    12 => 'ဒ',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'ဇန်နဝါရီ',
                    2  => 'ဖေဖော်ဝါရီ',
                    3  => 'မတ်',
                    4  => 'ဧပြီ',
                    5  => 'မေ',
                    6  => 'ဇွန်',
                    7  => 'ဇူလိုင်',
                    8  => 'ဩဂုတ်',
                    9  => 'စက်တင်ဘာ',
                    10 => 'အောက်တိုဘာ',
                    11 => 'နိုဝင်ဘာ',
                    12 => 'ဒီဇင်ဘာ',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'တနင်္ဂနွေ',
                    1 => 'တနင်္လာ',
                    2 => 'အင်္ဂါ',
                    3 => 'ဗုဒ္ဓဟူး',
                    4 => 'ကြာသပတေး',
                    5 => 'သောကြာ',
                    6 => 'စနေ',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'တ',
                    1 => 'တ',
                    2 => 'အ',
                    3 => 'ဗ',
                    4 => 'က',
                    5 => 'သ',
                    6 => 'စ',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'တနင်္ဂနွေ',
                    1 => 'တနင်္လာ',
                    2 => 'အင်္ဂါ',
                    3 => 'ဗုဒ္ဓဟူး',
                    4 => 'ကြာသပတေး',
                    5 => 'သောကြာ',
                    6 => 'စနေ',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, other {# နှစ်}}',
            'month'       => '{n, plural, other {# လ}}',
            'week'        => '{n, plural, other {# ပတ်}}',
            'day'         => '{n, plural, other {# ရက်}}',
            'hour'        => '{n, plural, other {# နာရီ}}',
            'minute'      => '{n, plural, other {# မိနစ်}}',
            'second'      => '{n, plural, other {# sec}}',
            'millisecond' => '{n, plural, other {# မီလီစက္ကန့်}}',
            'microsecond' => '{n, plural, other {# μs}}',
            'nanosecond'  => '{n, plural, other {# ns}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
