<?php
declare(strict_types=1);

/**
 * Locale data for 'km-KH'.
 * Created: Sun, 22 Nov 2020 20:21:17 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_km_KH_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = '.';
        $this->currencyFormat = '%f¤';
        $this->currencyNegativeFormat = '(%f¤)';
        $this->language = 'km';
        $this->locale = 'km-KH';
        $this->firstDayWeek = 0;
        $this->longDate = 'j F Y';
        $this->shortDate = 'j M Y';
        $this->longTime = 'g:i:s A';
        $this->shortTime = 'g:i A';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'AM';
        $this->pmString = 'PM';
        $this->nameEnglish = 'Khmer (Cambodia)';
        $this->nameNative = 'ខ្មែរ (កម្ពុជា)';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'មករា',
                      2 => 'កុម្ភៈ',
                      3 => 'មីនា',
                      4 => 'មេសា',
                      5 => 'ឧសភា',
                      6 => 'មិថុនា',
                      7 => 'កក្កដា',
                      8 => 'សីហា',
                      9 => 'កញ្ញា',
                      10 => 'តុលា',
                      11 => 'វិច្ឆិកា',
                      12 => 'ធ្នូ',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => 'ម',
                      2 => 'ក',
                      3 => 'ម',
                      4 => 'ម',
                      5 => 'ឧ',
                      6 => 'ម',
                      7 => 'ក',
                      8 => 'ស',
                      9 => 'ក',
                      10 => 'ត',
                      11 => 'វ',
                      12 => 'ធ',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'មករា',
                      2 => 'កុម្ភៈ',
                      3 => 'មីនា',
                      4 => 'មេសា',
                      5 => 'ឧសភា',
                      6 => 'មិថុនា',
                      7 => 'កក្កដា',
                      8 => 'សីហា',
                      9 => 'កញ្ញា',
                      10 => 'តុលា',
                      11 => 'វិច្ឆិកា',
                      12 => 'ធ្នូ',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'អាទិត្យ',
                      1 => 'ចន្ទ',
                      2 => 'អង្គារ',
                      3 => 'ពុធ',
                      4 => 'ព្រហ',
                      5 => 'សុក្រ',
                      6 => 'សៅរ៍',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'អ',
                      1 => 'ច',
                      2 => 'អ',
                      3 => 'ព',
                      4 => 'ព',
                      5 => 'ស',
                      6 => 'ស',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'អាទិត្យ',
                      1 => 'ច័ន្ទ',
                      2 => 'អង្គារ',
                      3 => 'ពុធ',
                      4 => 'ព្រហស្បតិ៍',
                      5 => 'សុក្រ',
                      6 => 'សៅរ៍',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, other {# ឆ្នាំ}}',
              'month' => '{n, plural, other {# ខែ}}',
              'week' => '{n, plural, other {# សប្ដាហ៍}}',
              'day' => '{n, plural, other {# ថ្ងៃ}}',
              'hour' => '{n, plural, other {# ម៉ោង}}',
              'minute' => '{n, plural, other {# នាទី}}',
              'second' => '{n, plural, other {# វិនាទី}}',
              'millisecond' => '{n, plural, other {# ម.វិ}}',
              'microsecond' => '{n, plural, other {# μs}}',
              'nanosecond' => '{n, plural, other {# ns}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
