<?php

declare(strict_types=1);

/**
 * Locale data for 'yo'.
 * Created: Tue, 01 Nov 2022 12:00:36 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_yo_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'yo';
        $this->locale = 'yo';
        $this->firstDayWeek = 1;
        $this->longDate = 'j M Y';
        $this->shortDate = 'j m Y';
        $this->longTime = 'G:i:s';
        $this->shortTime = 'G:i';
        $this->dateTime = '%date% %time%';
        $this->amString = 'Àárọ̀';
        $this->pmString = 'Ọ̀sán';
        $this->nameEnglish = 'Yoruba';
        $this->nameNative = 'Èdè Yorùbá';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'Ṣẹ́r',
                    2  => 'Èrèl',
                    3  => 'Ẹrẹ̀n',
                    4  => 'Ìgb',
                    5  => 'Ẹ̀bi',
                    6  => 'Òkú',
                    7  => 'Agẹ',
                    8  => 'Ògú',
                    9  => 'Owe',
                    10 => 'Ọ̀wà',
                    11 => 'Bél',
                    12 => 'Ọ̀pẹ',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'S',
                    2  => 'È',
                    3  => 'Ẹ',
                    4  => 'Ì',
                    5  => 'Ẹ̀',
                    6  => 'Ò',
                    7  => 'A',
                    8  => 'Ò',
                    9  => 'O',
                    10 => 'Ọ̀',
                    11 => 'B',
                    12 => 'Ọ̀',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'Oṣù Ṣẹ́rẹ́',
                    2  => 'Oṣù Èrèlè',
                    3  => 'Oṣù Ẹrẹ̀nà',
                    4  => 'Oṣù Ìgbé',
                    5  => 'Oṣù Ẹ̀bibi',
                    6  => 'Oṣù Òkúdu',
                    7  => 'Oṣù Agẹmọ',
                    8  => 'Oṣù Ògún',
                    9  => 'Oṣù Owewe',
                    10 => 'Oṣù Ọ̀wàrà',
                    11 => 'Oṣù Bélú',
                    12 => 'Oṣù Ọ̀pẹ̀',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'À',
                    1 => 'A',
                    2 => 'Ì',
                    3 => 'Ọ',
                    4 => 'Ọ',
                    5 => 'Ẹ',
                    6 => 'À',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'Ọjọ́ Àìkú',
                    1 => 'Ọjọ́ Ajé',
                    2 => 'Ọjọ́ Ìsẹ́gun',
                    3 => 'Ọjọ́rú',
                    4 => 'Ọjọ́bọ',
                    5 => 'Ọjọ́ Ẹtì',
                    6 => 'Ọjọ́ Àbámẹ́ta',
                ];
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'Àìk',
                    1 => 'Aj',
                    2 => 'Ìsẹ́g',
                    3 => 'Ọjọ́r',
                    4 => 'Ọjọ́b',
                    5 => 'Ẹt',
                    6 => 'Àbám',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, other {# ọd}}',
            'month'       => '{n, plural, other {# oṣù}}',
            'week'        => '{n, plural, other {# ọṣ}}',
            'day'         => '{n, plural, other {ọj #}}',
            'hour'        => '{n, plural, other {# wkt}}',
            'minute'      => '{n, plural, other {# ìṣ}}',
            'second'      => '{n, plural, other {# ìṣ àáy}}',
            'millisecond' => '{n, plural, one {# ms} other {# ms}}',
            'microsecond' => '{n, plural, one {# μs} other {# μs}}',
            'nanosecond'  => '{n, plural, one {# ns} other {# ns}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
