<?php

declare(strict_types=1);

/**
 * Locale data for 'lb'.
 * Created: Tue, 01 Nov 2022 12:00:27 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_lb_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = '.';
        $this->currencyFormat = '%f ¤';
        $this->currencyNegativeFormat = '%f ¤';
        $this->language = 'lb';
        $this->locale = 'lb';
        $this->firstDayWeek = 1;
        $this->longDate = 'j. F Y';
        $this->shortDate = 'j. M Y';
        $this->longTime = 'H:i:s';
        $this->shortTime = 'H:i';
        $this->dateTime = '%date% %time%';
        $this->amString = 'moies';
        $this->pmString = 'nomëttes';
        $this->nameEnglish = 'Luxembourgish';
        $this->nameNative = 'Lëtzebuergesch';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'Jan.',
                    2  => 'Feb.',
                    3  => 'Mäe.',
                    4  => 'Abr.',
                    5  => 'Mee',
                    6  => 'Juni',
                    7  => 'Juli',
                    8  => 'Aug.',
                    9  => 'Sep.',
                    10 => 'Okt.',
                    11 => 'Nov.',
                    12 => 'Dez.',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'J',
                    2  => 'F',
                    3  => 'M',
                    4  => 'A',
                    5  => 'M',
                    6  => 'J',
                    7  => 'J',
                    8  => 'A',
                    9  => 'S',
                    10 => 'O',
                    11 => 'N',
                    12 => 'D',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'Januar',
                    2  => 'Februar',
                    3  => 'Mäerz',
                    4  => 'Abrëll',
                    5  => 'Mee',
                    6  => 'Juni',
                    7  => 'Juli',
                    8  => 'August',
                    9  => 'September',
                    10 => 'Oktober',
                    11 => 'November',
                    12 => 'Dezember',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'Son.',
                    1 => 'Méi.',
                    2 => 'Dën.',
                    3 => 'Mët.',
                    4 => 'Don.',
                    5 => 'Fre.',
                    6 => 'Sam.',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'S',
                    1 => 'M',
                    2 => 'D',
                    3 => 'M',
                    4 => 'D',
                    5 => 'F',
                    6 => 'S',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'Sonndeg',
                    1 => 'Méindeg',
                    2 => 'Dënschdeg',
                    3 => 'Mëttwoch',
                    4 => 'Donneschdeg',
                    5 => 'Freideg',
                    6 => 'Samschdeg',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, one {# Joer} other {# Joer}}',
            'month'       => '{n, plural, one {# Mount} other {# Méint}}',
            'week'        => '{n, plural, one {# Woch} other {# Wochen}}',
            'day'         => '{n, plural, one {# Dag} other {# Deeg}}',
            'hour'        => '{n, plural, one {# St.} other {# St.}}',
            'minute'      => '{n, plural, one {# Min.} other {# Min.}}',
            'second'      => '{n, plural, one {# Sek.} other {# Sek.}}',
            'millisecond' => '{n, plural, one {# ms} other {# ms}}',
            'microsecond' => '{n, plural, one {# μs} other {# μs}}',
            'nanosecond'  => '{n, plural, one {# ns} other {# ns}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
