<?php

declare(strict_types=1);

/**
 * Locale data for 'fi-FI'.
 * Created: Tue, 01 Nov 2022 12:00:23 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_fi_FI_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = ' ';
        $this->currencyFormat = '%f ¤';
        $this->currencyNegativeFormat = '%f ¤';
        $this->language = 'fi';
        $this->locale = 'fi-FI';
        $this->firstDayWeek = 1;
        $this->longDate = 'j. F Y';
        $this->shortDate = 'j.n.Y';
        $this->longTime = 'G.i.s';
        $this->shortTime = 'G.i';
        $this->dateTime = '%date% %time%';
        $this->amString = 'ap.';
        $this->pmString = 'ip.';
        $this->nameEnglish = 'Finnish (Finland)';
        $this->nameNative = 'Suomi (Suomi)';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'Tammik.',
                    2  => 'Helmik.',
                    3  => 'Maalisk.',
                    4  => 'Huhtik.',
                    5  => 'Toukok.',
                    6  => 'Kesäk.',
                    7  => 'Heinäk.',
                    8  => 'Elok.',
                    9  => 'Syysk.',
                    10 => 'Lokak.',
                    11 => 'Marrask.',
                    12 => 'Jouluk.',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'T',
                    2  => 'H',
                    3  => 'M',
                    4  => 'H',
                    5  => 'T',
                    6  => 'K',
                    7  => 'H',
                    8  => 'E',
                    9  => 'S',
                    10 => 'L',
                    11 => 'M',
                    12 => 'J',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'Tammikuuta',
                    2  => 'Helmikuuta',
                    3  => 'Maaliskuuta',
                    4  => 'Huhtikuuta',
                    5  => 'Toukokuuta',
                    6  => 'Kesäkuuta',
                    7  => 'Heinäkuuta',
                    8  => 'Elokuuta',
                    9  => 'Syyskuuta',
                    10 => 'Lokakuuta',
                    11 => 'Marraskuuta',
                    12 => 'Joulukuuta',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'Su',
                    1 => 'Ma',
                    2 => 'Ti',
                    3 => 'Ke',
                    4 => 'To',
                    5 => 'Pe',
                    6 => 'La',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'S',
                    1 => 'M',
                    2 => 'T',
                    3 => 'K',
                    4 => 'T',
                    5 => 'P',
                    6 => 'L',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'Sunnuntaina',
                    1 => 'Maanantaina',
                    2 => 'Tiistaina',
                    3 => 'Keskiviikkona',
                    4 => 'Torstaina',
                    5 => 'Perjantaina',
                    6 => 'Lauantaina',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, one {# vuosi} one {# vuodesta} one {# vuoden} one {# vuoteen} one {# vuotta} other {# vuotta} other {# vuodesta} other {# vuoden} other {# vuoteen} other {# vuoteen}}',
            'month'       => '{n, plural, one {# kuukausi} one {# kuukaudesta} one {# kuukauden} one {# kuukauteen} one {# kuukautta} other {# kuukautta} other {# kuukaudesta} other {# kuukauden} other {# kuukauteen} other {# kuukautta}}',
            'week'        => '{n, plural, one {# viikko} one {# viikosta} one {# viikon} one {# viikkoon} one {# viikkoa} other {# viikkoa} other {# viikosta} other {# viikon} other {# viikkoon} other {# viikkoa}}',
            'day'         => '{n, plural, one {# päivä} one {# päivästä} one {# päivän} one {# päivään} one {# päivää} other {# päivää} other {# päivästä} other {# päivän} other {# päivään} other {# päivää}}',
            'hour'        => '{n, plural, one {# t} other {# t}}',
            'minute'      => '{n, plural, one {# min} other {# min}}',
            'second'      => '{n, plural, one {# s} other {# s}}',
            'millisecond' => '{n, plural, one {# ms} other {# ms}}',
            'microsecond' => '{n, plural, one {# μs} other {# μs}}',
            'nanosecond'  => '{n, plural, one {# ns} other {# ns}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
