<?php
declare(strict_types=1);

/**
 * Locale data for 'seh'.
 * Created: Sun, 22 Nov 2020 20:21:49 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_seh_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = '.';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'seh';
        $this->locale = 'seh';
        $this->firstDayWeek = 1;
        $this->longDate = 'j \\d\\e F \\d\\e Y';
        $this->shortDate = 'j \\d\\e M \\d\\e Y';
        $this->longTime = 'H:i:s';
        $this->shortTime = 'H:i';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'AM';
        $this->pmString = 'PM';
        $this->nameEnglish = 'English';
        $this->nameNative = 'English';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => 'J',
                      2 => 'F',
                      3 => 'M',
                      4 => 'A',
                      5 => 'M',
                      6 => 'J',
                      7 => 'J',
                      8 => 'A',
                      9 => 'S',
                      10 => 'O',
                      11 => 'N',
                      12 => 'D',
                    );
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'Jan',
                      2 => 'Fev',
                      3 => 'Mar',
                      4 => 'Abr',
                      5 => 'Mai',
                      6 => 'Jun',
                      7 => 'Jul',
                      8 => 'Aug',
                      9 => 'Set',
                      10 => 'Otu',
                      11 => 'Nov',
                      12 => 'Dec',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'Janeiro',
                      2 => 'Fevreiro',
                      3 => 'Marco',
                      4 => 'Abril',
                      5 => 'Maio',
                      6 => 'Junho',
                      7 => 'Julho',
                      8 => 'Augusto',
                      9 => 'Setembro',
                      10 => 'Otubro',
                      11 => 'Novembro',
                      12 => 'Decembro',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'D',
                      1 => 'P',
                      2 => 'C',
                      3 => 'T',
                      4 => 'N',
                      5 => 'S',
                      6 => 'S',
                    );
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'Dim',
                      1 => 'Pos',
                      2 => 'Pir',
                      3 => 'Tat',
                      4 => 'Nai',
                      5 => 'Sha',
                      6 => 'Sab',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'Dimingu',
                      1 => 'Chiposi',
                      2 => 'Chipiri',
                      3 => 'Chitatu',
                      4 => 'Chinai',
                      5 => 'Chishanu',
                      6 => 'Sabudu',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, one {# year} other {# years}}',
              'month' => '{n, plural, one {# month} other {# months}}',
              'week' => '{n, plural, one {# week} other {# weeks}}',
              'day' => '{n, plural, one {# day} other {# days}}',
              'hour' => '{n, plural, one {# hr} other {# hr}}',
              'minute' => '{n, plural, one {# min} other {# min}}',
              'second' => '{n, plural, one {# sec} other {# sec}}',
              'millisecond' => '{n, plural, one {# ms} other {# ms}}',
              'microsecond' => '{n, plural, one {# µs} other {# µs}}',
              'nanosecond' => '{n, plural, one {# ns} other {# ns}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
