<?php
declare(strict_types=1);

/**
 * Locale data for 'fa'.
 * Created: Sun, 22 Nov 2020 20:20:49 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_fa_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = '٫';
        $this->groupSeparator = '٬';
        $this->currencyFormat = '‎¤ %f';
        $this->currencyNegativeFormat = '‎(¤ %f)';
        $this->language = 'fa';
        $this->locale = 'fa';
        $this->firstDayWeek = 1;
        $this->longDate = 'j F Y';
        $this->shortDate = 'j M Y';
        $this->longTime = 'G:i:s';
        $this->shortTime = 'G:i';
        $this->dateTime = '%date%،‏ %time%';
        $this->amString = 'قبل‌ازظهر';
        $this->pmString = 'بعدازظهر';
        $this->nameEnglish = 'Persian';
        $this->nameNative = 'فارسی';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'ژانویهٔ',
                      2 => 'فوریهٔ',
                      3 => 'مارس',
                      4 => 'آوریل',
                      5 => 'مهٔ',
                      6 => 'ژوئن',
                      7 => 'ژوئیهٔ',
                      8 => 'اوت',
                      9 => 'سپتامبر',
                      10 => 'اکتبر',
                      11 => 'نوامبر',
                      12 => 'دسامبر',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => 'ژ',
                      2 => 'ف',
                      3 => 'م',
                      4 => 'آ',
                      5 => 'م',
                      6 => 'ژ',
                      7 => 'ژ',
                      8 => 'ا',
                      9 => 'س',
                      10 => 'ا',
                      11 => 'ن',
                      12 => 'د',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'ژانویهٔ',
                      2 => 'فوریهٔ',
                      3 => 'مارس',
                      4 => 'آوریل',
                      5 => 'مهٔ',
                      6 => 'ژوئن',
                      7 => 'ژوئیهٔ',
                      8 => 'اوت',
                      9 => 'سپتامبر',
                      10 => 'اکتبر',
                      11 => 'نوامبر',
                      12 => 'دسامبر',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'یکشنبه',
                      1 => 'دوشنبه',
                      2 => 'سه‌شنبه',
                      3 => 'چهارشنبه',
                      4 => 'پنجشنبه',
                      5 => 'جمعه',
                      6 => 'شنبه',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'ی',
                      1 => 'د',
                      2 => 'س',
                      3 => 'چ',
                      4 => 'پ',
                      5 => 'ج',
                      6 => 'ش',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'یکشنبه',
                      1 => 'دوشنبه',
                      2 => 'سه‌شنبه',
                      3 => 'چهارشنبه',
                      4 => 'پنجشنبه',
                      5 => 'جمعه',
                      6 => 'شنبه',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, one {# سال} other {# سال}}',
              'month' => '{n, plural, one {# ماه} other {# ماه}}',
              'week' => '{n, plural, one {# هفته} other {# هفته}}',
              'day' => '{n, plural, one {# روز} other {# روز}}',
              'hour' => '{n, plural, one {# ساعت} other {# ساعت}}',
              'minute' => '{n, plural, one {# دقیقه} other {# دقیقه}}',
              'second' => '{n, plural, one {# ثانیه} other {# ثانیه}}',
              'millisecond' => '{n, plural, one {# میلی‌ثانیه} other {# میلی‌ثانیه}}',
              'microsecond' => '{n, plural, one {# میکروثانیه} other {# <LRM>µs}}',
              'nanosecond' => '{n, plural, one {# <LRM>ns} other {# <LRM>ns}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
