<?php
declare(strict_types=1);

/**
 * Locale data for 'he'.
 * Created: Sun, 22 Nov 2020 20:21:05 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_he_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '%f ¤';
        $this->currencyNegativeFormat = '%f ¤';
        $this->language = 'he';
        $this->locale = 'he';
        $this->firstDayWeek = 1;
        $this->longDate = 'j בF Y';
        $this->shortDate = 'j בM Y';
        $this->longTime = 'G:i:s';
        $this->shortTime = 'G:i';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'לפנה״צ';
        $this->pmString = 'אחה״צ';
        $this->nameEnglish = 'Hebrew';
        $this->nameNative = 'עברית';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'ינו׳',
                      2 => 'פבר׳',
                      3 => 'מרץ',
                      4 => 'אפר׳',
                      5 => 'מאי',
                      6 => 'יוני',
                      7 => 'יולי',
                      8 => 'אוג׳',
                      9 => 'ספט׳',
                      10 => 'אוק׳',
                      11 => 'נוב׳',
                      12 => 'דצמ׳',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => '1',
                      2 => '2',
                      3 => '3',
                      4 => '4',
                      5 => '5',
                      6 => '6',
                      7 => '7',
                      8 => '8',
                      9 => '9',
                      10 => '10',
                      11 => '11',
                      12 => '12',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'ינואר',
                      2 => 'פברואר',
                      3 => 'מרץ',
                      4 => 'אפריל',
                      5 => 'מאי',
                      6 => 'יוני',
                      7 => 'יולי',
                      8 => 'אוגוסט',
                      9 => 'ספטמבר',
                      10 => 'אוקטובר',
                      11 => 'נובמבר',
                      12 => 'דצמבר',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'יום א׳',
                      1 => 'יום ב׳',
                      2 => 'יום ג׳',
                      3 => 'יום ד׳',
                      4 => 'יום ה׳',
                      5 => 'יום ו׳',
                      6 => 'שבת',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'א׳',
                      1 => 'ב׳',
                      2 => 'ג׳',
                      3 => 'ד׳',
                      4 => 'ה׳',
                      5 => 'ו׳',
                      6 => 'ש׳',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'יום ראשון',
                      1 => 'יום שני',
                      2 => 'יום שלישי',
                      3 => 'יום רביעי',
                      4 => 'יום חמישי',
                      5 => 'יום שישי',
                      6 => 'יום שבת',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, one {שנה} two {שנתיים} many {# שנים} other {# שנים}}',
              'month' => '{n, plural, one {חודש} two {חודשיים} many {# חודשים} other {# חודשים}}',
              'week' => '{n, plural, one {שבוע} two {שבועיים} many {# שבועות} other {# שבועות}}',
              'day' => '{n, plural, one {יום #} two {יומיים} many {# יום} other {# ימים}}',
              'hour' => '{n, plural, one {שעה} two {שעתיים} many {# שע׳} other {# שע׳}}',
              'minute' => '{n, plural, one {דקה} two {שתי דק׳} many {# דק׳} other {# דק׳}}',
              'second' => '{n, plural, one {שנ׳} two {שתי שנ׳} many {# שנ׳} other {# שנ׳}}',
              'millisecond' => '{n, plural, one {# ms} two {# ms} many {# ms} other {# ms}}',
              'microsecond' => '{n, plural, one {# μs} two {# μs} many {# μs} other {# μs}}',
              'nanosecond' => '{n, plural, one {# ns} two {# ns} many {# ns} other {# ns}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
