<?php
declare(strict_types=1);

/**
 * Locale data for 'luo'.
 * Created: Sun, 22 Nov 2020 20:21:24 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_luo_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'luo';
        $this->locale = 'luo';
        $this->firstDayWeek = 1;
        $this->longDate = 'j F Y';
        $this->shortDate = 'j M Y';
        $this->longTime = 'H:i:s';
        $this->shortTime = 'H:i';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'OD';
        $this->pmString = 'OT';
        $this->nameEnglish = 'English';
        $this->nameNative = 'English';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => 'C',
                      2 => 'R',
                      3 => 'D',
                      4 => 'N',
                      5 => 'B',
                      6 => 'U',
                      7 => 'B',
                      8 => 'B',
                      9 => 'C',
                      10 => 'P',
                      11 => 'C',
                      12 => 'P',
                    );
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'DAC',
                      2 => 'DAR',
                      3 => 'DAD',
                      4 => 'DAN',
                      5 => 'DAH',
                      6 => 'DAU',
                      7 => 'DAO',
                      8 => 'DAB',
                      9 => 'DOC',
                      10 => 'DAP',
                      11 => 'DGI',
                      12 => 'DAG',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'Dwe mar Achiel',
                      2 => 'Dwe mar Ariyo',
                      3 => 'Dwe mar Adek',
                      4 => 'Dwe mar Ang’wen',
                      5 => 'Dwe mar Abich',
                      6 => 'Dwe mar Auchiel',
                      7 => 'Dwe mar Abiriyo',
                      8 => 'Dwe mar Aboro',
                      9 => 'Dwe mar Ochiko',
                      10 => 'Dwe mar Apar',
                      11 => 'Dwe mar gi achiel',
                      12 => 'Dwe mar Apar gi ariyo',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'J',
                      1 => 'W',
                      2 => 'T',
                      3 => 'T',
                      4 => 'T',
                      5 => 'T',
                      6 => 'N',
                    );
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'JMP',
                      1 => 'WUT',
                      2 => 'TAR',
                      3 => 'TAD',
                      4 => 'TAN',
                      5 => 'TAB',
                      6 => 'NGS',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'Jumapil',
                      1 => 'Wuok Tich',
                      2 => 'Tich Ariyo',
                      3 => 'Tich Adek',
                      4 => 'Tich Ang’wen',
                      5 => 'Tich Abich',
                      6 => 'Ngeso',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, one {# year} other {# years}}',
              'month' => '{n, plural, one {# month} other {# months}}',
              'week' => '{n, plural, one {# week} other {# weeks}}',
              'day' => '{n, plural, one {# day} other {# days}}',
              'hour' => '{n, plural, one {# hr} other {# hr}}',
              'minute' => '{n, plural, one {# min} other {# min}}',
              'second' => '{n, plural, one {# sec} other {# sec}}',
              'millisecond' => '{n, plural, one {# ms} other {# ms}}',
              'microsecond' => '{n, plural, one {# µs} other {# µs}}',
              'nanosecond' => '{n, plural, one {# ns} other {# ns}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
