<?php

declare(strict_types=1);

/**
 * Locale data for 'ga-GB'.
 * Created: Tue, 01 Nov 2022 12:00:24 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_ga_GB_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'ga';
        $this->locale = 'ga-GB';
        $this->firstDayWeek = 1;
        $this->longDate = 'j F Y';
        $this->shortDate = 'j M Y';
        $this->longTime = 'H:i:s';
        $this->shortTime = 'H:i';
        $this->dateTime = '%date% %time%';
        $this->amString = 'r.n.';
        $this->pmString = 'i.n.';
        $this->nameEnglish = 'Irish (UK)';
        $this->nameNative = 'Gaeilge (an Ríocht Aontaithe)';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'Ean',
                    2  => 'Feabh',
                    3  => 'Márta',
                    4  => 'Aib',
                    5  => 'Beal',
                    6  => 'Meith',
                    7  => 'Iúil',
                    8  => 'Lún',
                    9  => 'MFómh',
                    10 => 'DFómh',
                    11 => 'Samh',
                    12 => 'Noll',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'E',
                    2  => 'F',
                    3  => 'M',
                    4  => 'A',
                    5  => 'B',
                    6  => 'M',
                    7  => 'I',
                    8  => 'L',
                    9  => 'M',
                    10 => 'D',
                    11 => 'S',
                    12 => 'N',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'Eanáir',
                    2  => 'Feabhra',
                    3  => 'Márta',
                    4  => 'Aibreán',
                    5  => 'Bealtaine',
                    6  => 'Meitheamh',
                    7  => 'Iúil',
                    8  => 'Lúnasa',
                    9  => 'Meán Fómhair',
                    10 => 'Deireadh Fómhair',
                    11 => 'Samhain',
                    12 => 'Nollaig',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'Domh',
                    1 => 'Luan',
                    2 => 'Máirt',
                    3 => 'Céad',
                    4 => 'Déar',
                    5 => 'Aoine',
                    6 => 'Sath',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'D',
                    1 => 'L',
                    2 => 'M',
                    3 => 'C',
                    4 => 'D',
                    5 => 'A',
                    6 => 'S',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'Dé Domhnaigh',
                    1 => 'Dé Luain',
                    2 => 'Dé Máirt',
                    3 => 'Dé Céadaoin',
                    4 => 'Déardaoin',
                    5 => 'Dé hAoine',
                    6 => 'Dé Sathairn',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, one {# bhliain} two {# bhliain} few {# bliana} many {# mbliana} other {# bliain}}',
            'month'       => '{n, plural, one {# mhí} two {# mhí} few {# mhí} many {# mí} other {# mí}}',
            'week'        => '{n, plural, one {# seachtain} two {# sheachtain} few {# seachtaine} many {# seachtaine} other {# seachtain}}',
            'day'         => '{n, plural, one {# lá} two {# lá} few {# lá} many {# lá} other {# lá}}',
            'hour'        => '{n, plural, one {# u} two {# u} few {# u} many {# u} other {# u}}',
            'minute'      => '{n, plural, one {# nóim} two {# nóim} few {# nóim} many {# nóim} other {# nóim}}',
            'second'      => '{n, plural, one {# soic} two {# shoic} few {# shoic} many {# soic} other {# soic}}',
            'millisecond' => '{n, plural, one {# ms} two {# ms} few {# ms} many {# ms} other {# ms}}',
            'microsecond' => '{n, plural, one {# μs} two {# μs} few {# μs} many {# μs} other {# μs}}',
            'nanosecond'  => '{n, plural, one {# ns} two {# ns} few {# ns} many {# ns} other {# ns}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
