<?php
declare(strict_types=1);

/**
 * Locale data for 'it-SM'.
 * Created: Sun, 22 Nov 2020 20:21:12 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_it_SM_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = '.';
        $this->currencyFormat = '%f ¤';
        $this->currencyNegativeFormat = '%f ¤';
        $this->language = 'it';
        $this->locale = 'it-SM';
        $this->firstDayWeek = 1;
        $this->longDate = 'j F Y';
        $this->shortDate = 'j M Y';
        $this->longTime = 'H:i:s';
        $this->shortTime = 'H:i';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'AM';
        $this->pmString = 'PM';
        $this->nameEnglish = 'Italian (San Marino)';
        $this->nameNative = 'Italiano (San Marino)';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'Gen',
                      2 => 'Feb',
                      3 => 'Mar',
                      4 => 'Apr',
                      5 => 'Mag',
                      6 => 'Giu',
                      7 => 'Lug',
                      8 => 'Ago',
                      9 => 'Set',
                      10 => 'Ott',
                      11 => 'Nov',
                      12 => 'Dic',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => 'G',
                      2 => 'F',
                      3 => 'M',
                      4 => 'A',
                      5 => 'M',
                      6 => 'G',
                      7 => 'L',
                      8 => 'A',
                      9 => 'S',
                      10 => 'O',
                      11 => 'N',
                      12 => 'D',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'Gennaio',
                      2 => 'Febbraio',
                      3 => 'Marzo',
                      4 => 'Aprile',
                      5 => 'Maggio',
                      6 => 'Giugno',
                      7 => 'Luglio',
                      8 => 'Agosto',
                      9 => 'Settembre',
                      10 => 'Ottobre',
                      11 => 'Novembre',
                      12 => 'Dicembre',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'Dom',
                      1 => 'Lun',
                      2 => 'Mar',
                      3 => 'Mer',
                      4 => 'Gio',
                      5 => 'Ven',
                      6 => 'Sab',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'D',
                      1 => 'L',
                      2 => 'M',
                      3 => 'M',
                      4 => 'G',
                      5 => 'V',
                      6 => 'S',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'Domenica',
                      1 => 'Lunedì',
                      2 => 'Martedì',
                      3 => 'Mercoledì',
                      4 => 'Giovedì',
                      5 => 'Venerdì',
                      6 => 'Sabato',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, one {# anno} other {# anni}}',
              'month' => '{n, plural, one {# mese} other {# mesi}}',
              'week' => '{n, plural, one {# settimana} other {# settimane}}',
              'day' => '{n, plural, one {# giorno} other {# giorni}}',
              'hour' => '{n, plural, one {# h} other {# h}}',
              'minute' => '{n, plural, one {# min} other {# min}}',
              'second' => '{n, plural, one {# s} other {# s}}',
              'millisecond' => '{n, plural, one {# ms} other {# ms}}',
              'microsecond' => '{n, plural, one {# μs} other {# μs}}',
              'nanosecond' => '{n, plural, one {# ns} other {# ns}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
