<?php
declare(strict_types=1);

/**
 * Locale data for 'haw-US'.
 * Created: Sun, 22 Nov 2020 20:21:04 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_haw_US_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'haw';
        $this->locale = 'haw-US';
        $this->firstDayWeek = 0;
        $this->longDate = 'j F Y';
        $this->shortDate = 'j M Y';
        $this->longTime = 'g:i:s A';
        $this->shortTime = 'g:i A';
        $this->dateTime = '%date% %time%';
        $this->amString = 'AM';
        $this->pmString = 'PM';
        $this->nameEnglish = 'English';
        $this->nameNative = 'English';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'Ian.',
                      2 => 'Pep.',
                      3 => 'Mal.',
                      4 => 'ʻAp.',
                      5 => 'Mei',
                      6 => 'Iun.',
                      7 => 'Iul.',
                      8 => 'ʻAu.',
                      9 => 'Kep.',
                      10 => 'ʻOk.',
                      11 => 'Now.',
                      12 => 'Kek.',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => '1',
                      2 => '2',
                      3 => '3',
                      4 => '4',
                      5 => '5',
                      6 => '6',
                      7 => '7',
                      8 => '8',
                      9 => '9',
                      10 => '10',
                      11 => '11',
                      12 => '12',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'Ianuali',
                      2 => 'Pepeluali',
                      3 => 'Malaki',
                      4 => 'ʻApelila',
                      5 => 'Mei',
                      6 => 'Iune',
                      7 => 'Iulai',
                      8 => 'ʻAukake',
                      9 => 'Kepakemapa',
                      10 => 'ʻOkakopa',
                      11 => 'Nowemapa',
                      12 => 'Kekemapa',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'LP',
                      1 => 'P1',
                      2 => 'P2',
                      3 => 'P3',
                      4 => 'P4',
                      5 => 'P5',
                      6 => 'P6',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'S',
                      1 => 'M',
                      2 => 'T',
                      3 => 'W',
                      4 => 'T',
                      5 => 'F',
                      6 => 'S',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'Lāpule',
                      1 => 'Poʻakahi',
                      2 => 'Poʻalua',
                      3 => 'Poʻakolu',
                      4 => 'Poʻahā',
                      5 => 'Poʻalima',
                      6 => 'Poʻaono',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, one {# makahiki} other {# makahiki}}',
              'month' => '{n, plural, one {# mahina} other {# mahina}}',
              'week' => '{n, plural, one {# pule} other {# pule}}',
              'day' => '{n, plural, one {# lā} other {# lā}}',
              'hour' => '{n, plural, one {# hr} other {# hr}}',
              'minute' => '{n, plural, one {# min} other {# min}}',
              'second' => '{n, plural, one {# sec} other {# sec}}',
              'millisecond' => '{n, plural, one {# ms} other {# ms}}',
              'microsecond' => '{n, plural, one {# µs} other {# µs}}',
              'nanosecond' => '{n, plural, one {# ns} other {# ns}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
