<?php
declare(strict_types=1);

/**
 * Locale data for 'os-RU'.
 * Created: Sun, 22 Nov 2020 20:21:39 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_os_RU_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = ' ';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'os';
        $this->locale = 'os-RU';
        $this->firstDayWeek = 1;
        $this->longDate = 'j F, Y аз';
        $this->shortDate = 'd M Y аз';
        $this->longTime = 'H:i:s';
        $this->shortTime = 'H:i';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'ӕмбисбоны размӕ';
        $this->pmString = 'ӕмбисбоны фӕстӕ';
        $this->nameEnglish = 'Ossetic (Russia)';
        $this->nameNative = 'Ирон (Уӕрӕсе)';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'янв.',
                      2 => 'фев.',
                      3 => 'мар.',
                      4 => 'апр.',
                      5 => 'майы',
                      6 => 'июны',
                      7 => 'июлы',
                      8 => 'авг.',
                      9 => 'сен.',
                      10 => 'окт.',
                      11 => 'ноя.',
                      12 => 'дек.',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => 'Я',
                      2 => 'Ф',
                      3 => 'М',
                      4 => 'А',
                      5 => 'М',
                      6 => 'И',
                      7 => 'И',
                      8 => 'А',
                      9 => 'С',
                      10 => 'О',
                      11 => 'Н',
                      12 => 'Д',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'январы',
                      2 => 'февралы',
                      3 => 'мартъийы',
                      4 => 'апрелы',
                      5 => 'майы',
                      6 => 'июны',
                      7 => 'июлы',
                      8 => 'августы',
                      9 => 'сентябры',
                      10 => 'октябры',
                      11 => 'ноябры',
                      12 => 'декабры',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'хцб',
                      1 => 'крс',
                      2 => 'дцг',
                      3 => 'ӕрт',
                      4 => 'цпр',
                      5 => 'мрб',
                      6 => 'сбт',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'Х',
                      1 => 'К',
                      2 => 'Д',
                      3 => 'Ӕ',
                      4 => 'Ц',
                      5 => 'М',
                      6 => 'С',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'хуыцаубон',
                      1 => 'къуырисӕр',
                      2 => 'дыццӕг',
                      3 => 'ӕртыццӕг',
                      4 => 'цыппӕрӕм',
                      5 => 'майрӕмбон',
                      6 => 'сабат',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, one {# аз} other {# азы}}',
              'month' => '{n, plural, one {# мӕй} other {# мӕйы}}',
              'week' => '{n, plural, one {# къуыри} other {# къуырийы}}',
              'day' => '{n, plural, one {# бон} other {# боны}}',
              'hour' => '{n, plural, one {# с.} other {# с.}}',
              'minute' => '{n, plural, one {# мин.} other {# мин.}}',
              'second' => '{n, plural, one {# sec} other {# sec}}',
              'millisecond' => '{n, plural, one {# ms} other {# ms}}',
              'microsecond' => '{n, plural, one {# µs} other {# µs}}',
              'nanosecond' => '{n, plural, one {# ns} other {# ns}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
