<?php
declare(strict_types=1);

/**
 * Locale data for 'su-Latn'.
 * Created: Sun, 22 Nov 2020 20:21:54 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_su_Latn_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = '.';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'su';
        $this->locale = 'su-Latn';
        $this->firstDayWeek = 1;
        $this->longDate = 'j F Y';
        $this->shortDate = 'j M Y';
        $this->longTime = 'G.i.s';
        $this->shortTime = 'G.i';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'AM';
        $this->pmString = 'PM';
        $this->nameEnglish = 'Sundanese';
        $this->nameNative = 'Basa Sunda';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => 'J',
                      2 => 'P',
                      3 => 'M',
                      4 => 'A',
                      5 => 'M',
                      6 => 'J',
                      7 => 'J',
                      8 => 'A',
                      9 => 'S',
                      10 => 'O',
                      11 => 'N',
                      12 => 'D',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'Januari',
                      2 => 'Pébruari',
                      3 => 'Maret',
                      4 => 'April',
                      5 => 'Méi',
                      6 => 'Juni',
                      7 => 'Juli',
                      8 => 'Agustus',
                      9 => 'Séptémber',
                      10 => 'Oktober',
                      11 => 'Nopémber',
                      12 => 'Désémber',
                    );
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'Jan',
                      2 => 'Péb',
                      3 => 'Mar',
                      4 => 'Apr',
                      5 => 'Méi',
                      6 => 'Jun',
                      7 => 'Jul',
                      8 => 'Ags',
                      9 => 'Sép',
                      10 => 'Okt',
                      11 => 'Nop',
                      12 => 'Dés',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'Mng',
                      1 => 'Sen',
                      2 => 'Sal',
                      3 => 'Reb',
                      4 => 'Kem',
                      5 => 'Jum',
                      6 => 'Sap',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'M',
                      1 => 'S',
                      2 => 'S',
                      3 => 'R',
                      4 => 'K',
                      5 => 'J',
                      6 => 'S',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'Minggu',
                      1 => 'Senén',
                      2 => 'Salasa',
                      3 => 'Rebo',
                      4 => 'Kemis',
                      5 => 'Jumaah',
                      6 => 'Saptu',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, one {# year} other {# years}}',
              'month' => '{n, plural, one {# month} other {# months}}',
              'week' => '{n, plural, one {# week} other {# weeks}}',
              'day' => '{n, plural, one {# day} other {# days}}',
              'hour' => '{n, plural, one {# hr} other {# hr}}',
              'minute' => '{n, plural, one {# min} other {# min}}',
              'second' => '{n, plural, one {# sec} other {# sec}}',
              'millisecond' => '{n, plural, one {# ms} other {# ms}}',
              'microsecond' => '{n, plural, one {# µs} other {# µs}}',
              'nanosecond' => '{n, plural, one {# ns} other {# ns}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
