<?php
declare(strict_types=1);

/**
 * Locale data for 'sl-SI'.
 * Created: Sun, 22 Nov 2020 20:21:51 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_sl_SI_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = '.';
        $this->currencyFormat = '%f ¤';
        $this->currencyNegativeFormat = '(%f ¤)';
        $this->language = 'sl';
        $this->locale = 'sl-SI';
        $this->firstDayWeek = 1;
        $this->longDate = 'd. F Y';
        $this->shortDate = 'j. M Y';
        $this->longTime = 'H:i:s';
        $this->shortTime = 'H:i';
        $this->dateTime = '%date% %time%';
        $this->amString = 'dop.';
        $this->pmString = 'pop.';
        $this->nameEnglish = 'Slovenian (Slovenia)';
        $this->nameNative = 'Slovenščina (Slovenija)';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'Jan.',
                      2 => 'Feb.',
                      3 => 'Mar.',
                      4 => 'Apr.',
                      5 => 'Maj',
                      6 => 'Jun.',
                      7 => 'Jul.',
                      8 => 'Avg.',
                      9 => 'Sep.',
                      10 => 'Okt.',
                      11 => 'Nov.',
                      12 => 'Dec.',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => 'J',
                      2 => 'F',
                      3 => 'M',
                      4 => 'A',
                      5 => 'M',
                      6 => 'J',
                      7 => 'J',
                      8 => 'A',
                      9 => 'S',
                      10 => 'O',
                      11 => 'N',
                      12 => 'D',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'Januar',
                      2 => 'Februar',
                      3 => 'Marec',
                      4 => 'April',
                      5 => 'Maj',
                      6 => 'Junij',
                      7 => 'Julij',
                      8 => 'Avgust',
                      9 => 'September',
                      10 => 'Oktober',
                      11 => 'November',
                      12 => 'December',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'Ned.',
                      1 => 'Pon.',
                      2 => 'Tor.',
                      3 => 'Sre.',
                      4 => 'čet.',
                      5 => 'Pet.',
                      6 => 'Sob.',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'N',
                      1 => 'P',
                      2 => 'T',
                      3 => 'S',
                      4 => 'č',
                      5 => 'P',
                      6 => 'S',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'Nedelja',
                      1 => 'Ponedeljek',
                      2 => 'Torek',
                      3 => 'Sreda',
                      4 => 'četrtek',
                      5 => 'Petek',
                      6 => 'Sobota',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, one {# leto} two {# leti} few {# let} other {# let}}',
              'month' => '{n, plural, one {# mesec} two {# meseca} few {# mesecev} other {# mesecev}}',
              'week' => '{n, plural, one {# teden} two {# tedna} few {# tednov} other {# tednov}}',
              'day' => '{n, plural, one {# dan} two {# dneva} few {# dni} other {# dni}}',
              'hour' => '{n, plural, one {# h} two {# h} few {# h} other {# h}}',
              'minute' => '{n, plural, one {# min} two {# min} few {# min} other {# min}}',
              'second' => '{n, plural, one {# sek.} two {# sek.} few {# sek.} other {# sek.}}',
              'millisecond' => '{n, plural, one {# ms} two {# ms} few {# ms} other {# ms}}',
              'microsecond' => '{n, plural, one {# μs} two {# μs} few {# μs} other {# μs}}',
              'nanosecond' => '{n, plural, one {# ns} two {# ns} few {# ns} other {# ns}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
