<?php

declare(strict_types=1);

/**
 * Locale data for 'da-GL'.
 * Created: Tue, 01 Nov 2022 12:00:20 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_da_GL_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = ',';
        $this->groupSeparator = '.';
        $this->currencyFormat = '%f ¤';
        $this->currencyNegativeFormat = '%f ¤';
        $this->language = 'da';
        $this->locale = 'da-GL';
        $this->firstDayWeek = 1;
        $this->longDate = 'j. F Y';
        $this->shortDate = 'j. M Y';
        $this->longTime = 'H.i.s';
        $this->shortTime = 'H.i';
        $this->dateTime = '%date% %time%';
        $this->amString = 'AM';
        $this->pmString = 'PM';
        $this->nameEnglish = 'Danish (Greenland)';
        $this->nameNative = 'Dansk (Grønland)';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'Jan.',
                    2  => 'Feb.',
                    3  => 'Mar.',
                    4  => 'Apr.',
                    5  => 'Maj',
                    6  => 'Jun.',
                    7  => 'Jul.',
                    8  => 'Aug.',
                    9  => 'Sep.',
                    10 => 'Okt.',
                    11 => 'Nov.',
                    12 => 'Dec.',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'J',
                    2  => 'F',
                    3  => 'M',
                    4  => 'A',
                    5  => 'M',
                    6  => 'J',
                    7  => 'J',
                    8  => 'A',
                    9  => 'S',
                    10 => 'O',
                    11 => 'N',
                    12 => 'D',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'Januar',
                    2  => 'Februar',
                    3  => 'Marts',
                    4  => 'April',
                    5  => 'Maj',
                    6  => 'Juni',
                    7  => 'Juli',
                    8  => 'August',
                    9  => 'September',
                    10 => 'Oktober',
                    11 => 'November',
                    12 => 'December',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'Søn.',
                    1 => 'Man.',
                    2 => 'Tirs.',
                    3 => 'Ons.',
                    4 => 'Tors.',
                    5 => 'Fre.',
                    6 => 'Lør.',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'S',
                    1 => 'M',
                    2 => 'T',
                    3 => 'O',
                    4 => 'T',
                    5 => 'F',
                    6 => 'L',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'Søndag',
                    1 => 'Mandag',
                    2 => 'Tirsdag',
                    3 => 'Onsdag',
                    4 => 'Torsdag',
                    5 => 'Fredag',
                    6 => 'Lørdag',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, one {# år} one {# års} other {# år} other {# års}}',
            'month'       => '{n, plural, one {# måned} one {# måneds} other {# måneder} other {# måneders}}',
            'week'        => '{n, plural, one {# uge} one {# uges} other {# uger} other {# ugers}}',
            'day'         => '{n, plural, one {# dag} one {# dags} other {# dage} other {# dages}}',
            'hour'        => '{n, plural, one {# t.} other {# t.}}',
            'minute'      => '{n, plural, one {# min.} other {# min.}}',
            'second'      => '{n, plural, one {# sek.} other {# sek.}}',
            'millisecond' => '{n, plural, one {# ms} other {# ms}}',
            'microsecond' => '{n, plural, one {# μs} other {# μs}}',
            'nanosecond'  => '{n, plural, one {# ns} other {# ns}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
