<?php

declare(strict_types=1);

/**
 * Locale data for 'kn-IN'.
 * Created: Tue, 01 Nov 2022 12:00:26 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_kn_IN_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'kn';
        $this->locale = 'kn-IN';
        $this->firstDayWeek = 0;
        $this->longDate = 'F j, Y';
        $this->shortDate = 'M j, Y';
        $this->longTime = 'h:i:s A';
        $this->shortTime = 'h:i A';
        $this->dateTime = '%date% %time%';
        $this->amString = 'ಪೂರ್ವಾಹ್ನ';
        $this->pmString = 'ಅಪರಾಹ್ನ';
        $this->nameEnglish = 'Kannada (India)';
        $this->nameNative = 'ಕನ್ನಡ (ಭಾರತ)';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'ಜನವರಿ',
                    2  => 'ಫೆಬ್ರವರಿ',
                    3  => 'ಮಾರ್ಚ್',
                    4  => 'ಏಪ್ರಿ',
                    5  => 'ಮೇ',
                    6  => 'ಜೂನ್',
                    7  => 'ಜುಲೈ',
                    8  => 'ಆಗಸ್ಟ್',
                    9  => 'ಸೆಪ್ಟೆಂ',
                    10 => 'ಅಕ್ಟೋ',
                    11 => 'ನವೆಂ',
                    12 => 'ಡಿಸೆಂ',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'ಜ',
                    2  => 'ಫೆ',
                    3  => 'ಮಾ',
                    4  => 'ಏ',
                    5  => 'ಮೇ',
                    6  => 'ಜೂ',
                    7  => 'ಜು',
                    8  => 'ಆ',
                    9  => 'ಸೆ',
                    10 => 'ಅ',
                    11 => 'ನ',
                    12 => 'ಡಿ',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'ಜನವರಿ',
                    2  => 'ಫೆಬ್ರವರಿ',
                    3  => 'ಮಾರ್ಚ್',
                    4  => 'ಏಪ್ರಿಲ್',
                    5  => 'ಮೇ',
                    6  => 'ಜೂನ್',
                    7  => 'ಜುಲೈ',
                    8  => 'ಆಗಸ್ಟ್',
                    9  => 'ಸೆಪ್ಟೆಂಬರ್',
                    10 => 'ಅಕ್ಟೋಬರ್',
                    11 => 'ನವೆಂಬರ್',
                    12 => 'ಡಿಸೆಂಬರ್',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'ಭಾನು',
                    1 => 'ಸೋಮ',
                    2 => 'ಮಂಗಳ',
                    3 => 'ಬುಧ',
                    4 => 'ಗುರು',
                    5 => 'ಶುಕ್ರ',
                    6 => 'ಶನಿ',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'ಭಾ',
                    1 => 'ಸೋ',
                    2 => 'ಮಂ',
                    3 => 'ಬು',
                    4 => 'ಗು',
                    5 => 'ಶು',
                    6 => 'ಶ',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'ಭಾನುವಾರ',
                    1 => 'ಸೋಮವಾರ',
                    2 => 'ಮಂಗಳವಾರ',
                    3 => 'ಬುಧವಾರ',
                    4 => 'ಗುರುವಾರ',
                    5 => 'ಶುಕ್ರವಾರ',
                    6 => 'ಶನಿವಾರ',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, one {# ವರ್ಷವು} one {# ವರ್ಷವನ್ನು} one {# ವರ್ಷಕ್ಕೆ} one {# ವರ್ಷದ} one {# ವರ್ಷದಲ್ಲಿ} other {# ವರ್ಷಗಳು} other {# ವರ್ಷಗಳನ್ನು} other {# ವರ್ಷಗಳಿಗೆ} other {# ವರ್ಷಗಳ} other {# ವರ್ಷಗಳಲ್ಲಿ}}',
            'month'       => '{n, plural, one {# ತಿಂಗಳು} one {# ತಿಂಗಳನ್ನು} one {# ತಿಂಗಳಿಗೆ} one {# ತಿಂಗಳ} one {# ತಿಂಗಳಲ್ಲಿ} other {# ತಿಂಗಳು} other {# ತಿಂಗಳುಗಳನ್ನು} other {# ತಿಂಗಳುಗಳಿಗೆ} other {# ತಿಂಗಳುಗಳ} other {# ತಿಂಗಳುಗಳಲ್ಲಿ} other {# ತಿಂಗಳುಗಳು}}',
            'week'        => '{n, plural, one {# ವಾರವು} one {# ವಾರವನ್ನು} one {# ವಾರಕ್ಕೆ} one {# ವಾರದ} one {# ವಾರದಲ್ಲಿ} other {# ವಾರಗಳು} other {# ವಾರಗಳನ್ನು} other {# ವಾರಗಳಿಗೆ} other {# ವಾರಗಳ} other {# ವಾರಗಳಲ್ಲಿ}}',
            'day'         => '{n, plural, one {# ದಿನವು} one {# ದಿನವನ್ನು} one {# ದಿನಕ್ಕೆ} one {# ದಿನದ} one {# ದಿನದಲ್ಲಿ} other {# ದಿನಗಳು} other {# ದಿನಗಳನ್ನು} other {# ದಿನಗಳಿಗೆ} other {# ದಿನಗಳ} other {# ದಿನಗಳಲ್ಲಿ}}',
            'hour'        => '{n, plural, one {# ಗಂ.} other {# ಗಂ.}}',
            'minute'      => '{n, plural, one {# ನಿಮಿ} other {# ನಿಮಿ}}',
            'second'      => '{n, plural, one {# ಸೆಕೆಂ} other {# ಸೆಕೆಂ}}',
            'millisecond' => '{n, plural, one {# ಮಿ.ಸೆ.} other {# ಮಿ.ಸೆ.}}',
            'microsecond' => '{n, plural, one {# μs} other {# μs}}',
            'nanosecond'  => '{n, plural, one {# ನ್ಯಾ.ಸೆ} other {# ನ್ಯಾ.ಸೆ}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
