<?php
declare(strict_types=1);

/**
 * Locale data for 'kok'.
 * Created: Sun, 22 Nov 2020 20:21:18 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_kok_Data extends i18n_Locale
{
    public function __construct() {
        // Version 38
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'kok';
        $this->locale = 'kok';
        $this->firstDayWeek = 1;
        $this->longDate = 'j F Y';
        $this->shortDate = 'j-M-Y';
        $this->longTime = 'g:i:s A';
        $this->shortTime = 'g:i A';
        $this->dateTime = '%date% %time%';
        $this->amString = 'AM';
        $this->pmString = 'PM';
        $this->nameEnglish = 'English';
        $this->nameNative = 'English';
    }
        
    public function months($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      1 => 'जानेवारी',
                      2 => 'फेब्रुवारी',
                      3 => 'मार्च',
                      4 => 'एप्रील',
                      5 => 'मे',
                      6 => 'जून',
                      7 => 'जुलय',
                      8 => 'ऑगस्ट',
                      9 => 'सप्टेंबर',
                      10 => 'ऑक्टोबर',
                      11 => 'नोव्हेंबर',
                      12 => 'डिसेंबर',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      1 => '1',
                      2 => '2',
                      3 => '3',
                      4 => '4',
                      5 => '5',
                      6 => '6',
                      7 => '7',
                      8 => '8',
                      9 => '9',
                      10 => '10',
                      11 => '11',
                      12 => '12',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      1 => 'जानेवारी',
                      2 => 'फेब्रुवारी',
                      3 => 'मार्च',
                      4 => 'एप्रील',
                      5 => 'मे',
                      6 => 'जून',
                      7 => 'जुलय',
                      8 => 'ऑगस्ट',
                      9 => 'सप्टेंबर',
                      10 => 'ऑक्टोबर',
                      11 => 'नोव्हेंबर',
                      12 => 'डिसेंबर',
                    );
        }
    }

        public function weekDays($type = i18n_Locale::TYPE_WIDE): array{
        switch($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return array (
                      0 => 'आयतार',
                      1 => 'सोमार',
                      2 => 'मंगळार',
                      3 => 'बुधवार',
                      4 => 'बिरेस्तार',
                      5 => 'शुक्रार',
                      6 => 'शेनवार',
                    );
            case i18n_Locale::TYPE_NARROW:
                return array (
                      0 => 'आ',
                      1 => 'सो',
                      2 => 'मं',
                      3 => 'बु',
                      4 => 'बि',
                      5 => 'शु',
                      6 => 'शे',
                    );
            case i18n_Locale::TYPE_WIDE:
                return array (
                      0 => 'आयतार',
                      1 => 'सोमार',
                      2 => 'मंगळार',
                      3 => 'बुधवार',
                      4 => 'बिरेस्तार',
                      5 => 'शुक्रार',
                      6 => 'शेनवार',
                    );
        }
    }

        public function intervals(): array{
                    return array (
              'year' => '{n, plural, other {# वर्सां}}',
              'month' => '{n, plural, other {# म्हयने}}',
              'week' => '{n, plural, other {# सप्तक}}',
              'day' => '{n, plural, other {# दीस}}',
              'hour' => '{n, plural, other {# वर}}',
              'minute' => '{n, plural, other {# मिनीट}}',
              'second' => '{n, plural, other {# सेकंद}}',
              'millisecond' => '{n, plural, other {# मिलिसेकंद}}',
              'microsecond' => '{n, plural, other {# μs}}',
              'nanosecond' => '{n, plural, other {# नॅसे}}',
            );
                }

        public function currencies(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
                }

        public function languages(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
                }

        public function territories(): array{
                   return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
                }
}
