<?php

declare(strict_types=1);

/**
 * Locale data for 'sd-Deva'.
 * Created: Tue, 01 Nov 2022 12:00:32 +0100
 *
 * This file is automatically generated using the data from the Unicode Common Locale Data Repository.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 */
class i18n_Locale_sd_Deva_Data extends i18n_Locale
{
    public function __construct()
    {
        // Version 42
        $this->orientation = 'ltr';
        $this->decimalSeparator = '.';
        $this->groupSeparator = ',';
        $this->currencyFormat = '¤%f';
        $this->currencyNegativeFormat = '(¤%f)';
        $this->language = 'sd';
        $this->locale = 'sd-Deva';
        $this->firstDayWeek = 1;
        $this->longDate = 'F j, Y';
        $this->shortDate = 'M j, Y';
        $this->longTime = 'g:i:s A';
        $this->shortTime = 'g:i A';
        $this->dateTime = '%date%, %time%';
        $this->amString = 'सुबुह जा';
        $this->pmString = 'शाम जा';
        $this->nameEnglish = 'Sindhi';
        $this->nameNative = 'سنڌي';
    }

    public function months($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    1  => 'जन',
                    2  => 'फर',
                    3  => 'मार्च',
                    4  => 'अप्रै',
                    5  => 'मई',
                    6  => 'जून',
                    7  => 'जु',
                    8  => 'अग',
                    9  => 'सप्टे',
                    10 => 'ऑक्टो',
                    11 => 'नवं',
                    12 => 'डिसं',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    1  => 'ज',
                    2  => 'फ़',
                    3  => 'मा',
                    4  => 'अ',
                    5  => 'मा',
                    6  => 'जू',
                    7  => 'जु',
                    8  => 'अग',
                    9  => 'स',
                    10 => 'ऑ',
                    11 => 'न',
                    12 => 'डि',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    1  => 'जनवरी',
                    2  => 'फरवरी',
                    3  => 'मार्चु',
                    4  => 'अप्रैल',
                    5  => 'मई',
                    6  => 'जून',
                    7  => 'जुलाई',
                    8  => 'अगस्ट',
                    9  => 'सप्टेंबर',
                    10 => 'ओक्टोबर',
                    11 => 'नवंबर',
                    12 => 'डिसंबर',
                ];
        }
    }

    public function weekDays($type = i18n_Locale::TYPE_WIDE): array
    {
        switch ($type) {
            case i18n_Locale::TYPE_ABBREVIATED:
                return [
                    0 => 'आर्त',
                    1 => 'सू',
                    2 => 'मंग',
                    3 => 'बु॒ध',
                    4 => 'विस',
                    5 => 'जुम',
                    6 => 'छंछ',
                ];
            case i18n_Locale::TYPE_NARROW:
                return [
                    0 => 'आ',
                    1 => 'सू',
                    2 => 'मं',
                    3 => 'बु॒',
                    4 => 'वि',
                    5 => 'जु',
                    6 => 'छं',
                ];
            case i18n_Locale::TYPE_WIDE:
                return [
                    0 => 'आर्तवार',
                    1 => 'सूमर',
                    2 => 'मंगलु',
                    3 => 'बु॒धर',
                    4 => 'विस्पत',
                    5 => 'जुमो',
                    6 => 'छंछर',
                ];
        }
    }

    public function intervals(): array
    {
        return [
            'year'        => '{n, plural, one {# سال} other {# سال}}',
            'month'       => '{n, plural, one {# مهينا} other {# مهينا}}',
            'week'        => '{n, plural, one {# هفتا} other {# هفتا}}',
            'day'         => '{n, plural, one {# ڏينهن} other {# ڏينهن}}',
            'hour'        => '{n, plural, one {# ڪلاڪ} other {# ڪلاڪ}}',
            'minute'      => '{n, plural, one {# منٽ} other {# منٽ}}',
            'second'      => '{n, plural, one {# سيڪنڊ} other {# سيڪنڊ}}',
            'millisecond' => '{n, plural, one {# ملي سيڪنڊ} other {# ملي سيڪنڊ}}',
            'microsecond' => '{n, plural, one {# مائڪرو سيڪنڊ} other {# مائڪرو سيڪنڊ}}',
            'nanosecond'  => '{n, plural, one {# نينو سيڪنڊ} other {# نينو سيڪنڊ}}',
        ];
    }

    public function currencies(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Currencies.php';
    }

    public function languages(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Languages.php';
    }

    public function territories(): array
    {
        return require __DIR__ . DIRECTORY_SEPARATOR . 'Territories.php';
    }
}
